# CI de Nível 01 - Disparo Manual através de clique

# nome da pipeline
name: 'N1 - Execução Manual'

# Permissões necessárias para a workflow
permissions:
  # Permite escrever no repositório (para commits e pushes)
  contents: write

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch

on:
  workflow_dispatch:

# Agendada
  schedule:
    # cronograma de execução
    # 1 - minuto, 2 - hora, 3 dia do mês, 4 - mês, 5 - dia da semana

    #Roda as 16:43
    - cron: '43 19 * * *'

  push:
    branches:
    - main

#tarefas dentro da pipeline = jobs

jobs:
  #nome do job
  test:
    # maquina onde o job vai rodar
    runs-on: ubuntu-latest

    # passos do job
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalção do node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      #   instalação das dependências
      - name: Instalando dependências
        run: yarn

      - name: Executar testes
        run: yarn test
      
      # Upload do relatório Mochawesome
      - name: Upload do relatório
        if: hashFiles('reports/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: reports/