# CI de Nível 01 - Disparo Manual através de clique

# nome da pipeline
name: 'N1 - Execução Manual'

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch

on:
  workflow_dispatch:

  schedule:
    # cronograma de execução
    # 1 - minuto, 2 - hora, 3 dia do mês, 4 - mês, 5 - dia da semana

    #Roda a cada 20 minutos
    - cron: '*/20 * * * *'

  push:
    branches:
    - main
    
#tarefas dentro da pipeline = jobs

jobs:
  #nome do job
  test:
    # maquina onde o job vai rodar
    runs-on: ubuntu-latest

    # passos do job
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalção do node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      #   instalação das dependências
      - name: Instalando dependências
        run: yarn

      # Upload do relatório Mochawesome
      - name: Upload do relatório Mochawesome
        if: hashFiles('reports/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: reports/